# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Gospel Ruben S
title: QA ENGINEER
email: gospelruben@gmail.com ; gospelruben.s@gmail.com
#phone: Your phone number (optional)
cv   : "Ruben Automation Resume-April2020.pdf"
#website: Your website (eg. https://google.com)(optional)

# Social links
#twitter_username: jekyllrb
#github_username:  gospelruben
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: gospel-ruben-a0476450
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile1.jpg
about_content: | # this will include new lines to allow paragraphs
  <b>4</b> Years of experience in Software Automation Testing and <b>2</b> Year of experience in Software Manual Testing.
  
  <b>Automation Testing Skills:</b> Web App(Selenium), Mobile App(Appium), Web Services Testing(REST), DataBase Testing(Selenium).
  
  <b>Manual Testing Skills:</b> Functional Testing, Regression Testing, ADA (American Disability Act),Data Validation Testing.
    
  <b>Domain Knowledge:</b> Insurance, Health Care, Gaming, Travel and Tourism, Finance.

  You can find my brief description in this [Resume](Ruben Automation Resume-April2020.pdf)
#- Tables
    #- Links
    #- Images

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
experience_title: Work Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: Technical Skills #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  <ul><li><b>Testing Tools:</b> Selenium WebDriver/IDE, WinApp Driver, Appium, Jenkins, Fire bug and Fire Path.</li>
  <li><b>Languages:</b> Java,SQL, XPath.</li>
  <li><b>Web Technologies:</b> HTML, CSS, Java,Regular Expression, log4j, JDBC.</li>
  <li><b>Unit Test Frameworks:</b> Cucumber, Junit, TestNG.</li>
  <li><b>Bug Tracking Tools:</b> Insight, HP ALM, JIRA, Confluence, Test Link.</li>
  <li><b>Web Services:</b> JMeter, POSTMAN, TAURUS, MonitoringTool(Grafana, Influx-DB).</li>
  <li><b>Version Control Tools:</b>GIT and GITHUB Desktop.</li>
  <li><b>Build Tools:</b> MAVEN.</li>
  <li><b>Databases:</b> SQL.</li>
  <li><b>Operating Systems:</b> Mac, Windows.</li>
  <li><b>Devices Used for Testing:</b> Android mobile, iOS mobile, Tablet, iPad.</li>
  <li><b>Continous Integration Tool:</b> Jenkins.</li>
  <li><b>ADA Testing Tools:</b> NVDA, Talkback for Android, Voice-Over for iOS, WAVE Evaluation Tool.</li></ul>
  

# Footer
#footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "makefile",
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
